/*
 * GmailAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities;
using GmailAPI.PCL.Http.Request;
using GmailAPI.PCL.Http.Response;
using GmailAPI.PCL.Http.Client;
using GmailAPI.PCL.Exceptions;
using GmailAPI.PCL.Models;

namespace GmailAPI.PCL.Controllers
{
    public partial class ThreadsController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static ThreadsController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static ThreadsController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new ThreadsController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// Removes the specified thread from the trash.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to remove from Trash.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the Thread response from the API call</return>
        public Thread CreateUntrash(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            Task<Thread> t = CreateUntrashAsync(id, userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Removes the specified thread from the trash.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to remove from Trash.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the Thread response from the API call</return>
        public async Task<Thread> CreateUntrashAsync(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/{userId}/threads/{id}/untrash");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "id", id },
                { "userId", (null != userId) ? userId : "me" }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "alt", (null != alt) ? alt : "json" },
                { "fields", fields },
                { "key", key },
                { "oauth_token", oauthToken },
                { "prettyPrint", (null != prettyPrint) ? prettyPrint : true },
                { "quotaUser", quotaUser },
                { "userIp", userIp }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };
            _headers.Add("Authorization", string.Format("Bearer {0}", Configuration.OAuthAccessToken));

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, null);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Thread>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Moves the specified thread to the trash.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to Trash.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the Thread response from the API call</return>
        public Thread CreateTrash(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            Task<Thread> t = CreateTrashAsync(id, userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Moves the specified thread to the trash.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to Trash.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the Thread response from the API call</return>
        public async Task<Thread> CreateTrashAsync(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/{userId}/threads/{id}/trash");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "id", id },
                { "userId", (null != userId) ? userId : "me" }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "alt", (null != alt) ? alt : "json" },
                { "fields", fields },
                { "key", key },
                { "oauth_token", oauthToken },
                { "prettyPrint", (null != prettyPrint) ? prettyPrint : true },
                { "quotaUser", quotaUser },
                { "userIp", userIp }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };
            _headers.Add("Authorization", string.Format("Bearer {0}", Configuration.OAuthAccessToken));

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, null);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Thread>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Modifies the labels applied to the thread. This applies to all messages in the thread.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to modify.</param>
        /// <param name="body">Required parameter: Example: </param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the Thread response from the API call</return>
        public Thread Modify(
                string id,
                ModifyThreadRequest body,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            Task<Thread> t = ModifyAsync(id, body, userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Modifies the labels applied to the thread. This applies to all messages in the thread.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to modify.</param>
        /// <param name="body">Required parameter: Example: </param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the Thread response from the API call</return>
        public async Task<Thread> ModifyAsync(
                string id,
                ModifyThreadRequest body,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/{userId}/threads/{id}/modify");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "id", id },
                { "userId", (null != userId) ? userId : "me" }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "alt", (null != alt) ? alt : "json" },
                { "fields", fields },
                { "key", key },
                { "oauth_token", oauthToken },
                { "prettyPrint", (null != prettyPrint) ? prettyPrint : true },
                { "quotaUser", quotaUser },
                { "userIp", userIp }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "content-type", "application/json; charset=utf-8" }
            };
            _headers.Add("Authorization", string.Format("Bearer {0}", Configuration.OAuthAccessToken));

            //append body params
            var _body = APIHelper.JsonSerialize(body);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.PostBody(_queryUrl, _headers, _body);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Thread>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Lists the threads in the user's mailbox.
        /// </summary>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <param name="includeSpamTrash">Optional parameter: Include threads from SPAM and TRASH in the results.</param>
        /// <param name="labelIds">Optional parameter: Only return threads with labels that match all of the specified label IDs.</param>
        /// <param name="maxResults">Optional parameter: Maximum number of threads to return.</param>
        /// <param name="pageToken">Optional parameter: Page token to retrieve a specific page of results in the list.</param>
        /// <param name="q">Optional parameter: Only return threads matching the specified query. Supports the same query format as the Gmail search box. For example, "from:someuser@example.com rfc822msgid: is:unread".</param>
        /// <return>Returns the ListThreadsResponse response from the API call</return>
        public ListThreadsResponse List(
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null,
                bool? includeSpamTrash = false,
                string labelIds = null,
                double? maxResults = 100,
                string pageToken = null,
                string q = null)
        {
            Task<ListThreadsResponse> t = ListAsync(userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp, includeSpamTrash, labelIds, maxResults, pageToken, q);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Lists the threads in the user's mailbox.
        /// </summary>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <param name="includeSpamTrash">Optional parameter: Include threads from SPAM and TRASH in the results.</param>
        /// <param name="labelIds">Optional parameter: Only return threads with labels that match all of the specified label IDs.</param>
        /// <param name="maxResults">Optional parameter: Maximum number of threads to return.</param>
        /// <param name="pageToken">Optional parameter: Page token to retrieve a specific page of results in the list.</param>
        /// <param name="q">Optional parameter: Only return threads matching the specified query. Supports the same query format as the Gmail search box. For example, "from:someuser@example.com rfc822msgid: is:unread".</param>
        /// <return>Returns the ListThreadsResponse response from the API call</return>
        public async Task<ListThreadsResponse> ListAsync(
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null,
                bool? includeSpamTrash = false,
                string labelIds = null,
                double? maxResults = 100,
                string pageToken = null,
                string q = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/{userId}/threads");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "userId", (null != userId) ? userId : "me" }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "alt", (null != alt) ? alt : "json" },
                { "fields", fields },
                { "key", key },
                { "oauth_token", oauthToken },
                { "prettyPrint", (null != prettyPrint) ? prettyPrint : true },
                { "quotaUser", quotaUser },
                { "userIp", userIp },
                { "includeSpamTrash", (null != includeSpamTrash) ? includeSpamTrash : false },
                { "labelIds", labelIds },
                { "maxResults", (null != maxResults) ? maxResults : 100 },
                { "pageToken", pageToken },
                { "q", q }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };
            _headers.Add("Authorization", string.Format("Bearer {0}", Configuration.OAuthAccessToken));

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<ListThreadsResponse>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Gets the specified thread.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to retrieve.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <param name="format">Optional parameter: The format to return the messages in. (Acceptable values are: "full", "metadata", "minimal")</param>
        /// <param name="metadataHeaders">Optional parameter: When given and format is METADATA, only include headers specified.</param>
        /// <return>Returns the Thread response from the API call</return>
        public Thread GetThreadsByUserIdAndId(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null,
                string format = "full",
                string metadataHeaders = null)
        {
            Task<Thread> t = GetThreadsByUserIdAndIdAsync(id, userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp, format, metadataHeaders);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// Gets the specified thread.
        /// </summary>
        /// <param name="id">Required parameter: The ID of the thread to retrieve.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <param name="format">Optional parameter: The format to return the messages in. (Acceptable values are: "full", "metadata", "minimal")</param>
        /// <param name="metadataHeaders">Optional parameter: When given and format is METADATA, only include headers specified.</param>
        /// <return>Returns the Thread response from the API call</return>
        public async Task<Thread> GetThreadsByUserIdAndIdAsync(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null,
                string format = "full",
                string metadataHeaders = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/{userId}/threads/{id}");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "id", id },
                { "userId", (null != userId) ? userId : "me" }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "alt", (null != alt) ? alt : "json" },
                { "fields", fields },
                { "key", key },
                { "oauth_token", oauthToken },
                { "prettyPrint", (null != prettyPrint) ? prettyPrint : true },
                { "quotaUser", quotaUser },
                { "userIp", userIp },
                { "format", (null != format) ? format : "full" },
                { "metadataHeaders", metadataHeaders }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };
            _headers.Add("Authorization", string.Format("Bearer {0}", Configuration.OAuthAccessToken));

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Thread>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer threads.trash instead.
        /// </summary>
        /// <param name="id">Required parameter: ID of the Thread to delete.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the void response from the API call</return>
        public void DeleteThreadsByUserIdAndId(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            Task t = DeleteThreadsByUserIdAndIdAsync(id, userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer threads.trash instead.
        /// </summary>
        /// <param name="id">Required parameter: ID of the Thread to delete.</param>
        /// <param name="userId">Optional parameter: The user's email address. The special value me can be used to indicate the authenticated user.</param>
        /// <param name="alt">Optional parameter: Data format for the response. (Acceptable values are: "json")</param>
        /// <param name="fields">Optional parameter: Selector specifying which fields to include in a partial response.</param>
        /// <param name="key">Optional parameter: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.</param>
        /// <param name="oauthToken">Optional parameter: OAuth 2.0 token for the current user.</param>
        /// <param name="prettyPrint">Optional parameter: Returns response with indentations and line breaks.</param>
        /// <param name="quotaUser">Optional parameter: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.</param>
        /// <param name="userIp">Optional parameter: IP address of the site where the request originates. Use this if you want to enforce per-user limits.</param>
        /// <return>Returns the void response from the API call</return>
        public async Task DeleteThreadsByUserIdAndIdAsync(
                string id,
                string userId = "me",
                string alt = "json",
                string fields = null,
                string key = null,
                string oauthToken = null,
                bool? prettyPrint = true,
                string quotaUser = null,
                string userIp = null)
        {
            //the base uri for api requestss
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/{userId}/threads/{id}");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "id", id },
                { "userId", (null != userId) ? userId : "me" }
            });

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "alt", (null != alt) ? alt : "json" },
                { "fields", fields },
                { "key", key },
                { "oauth_token", oauthToken },
                { "prettyPrint", (null != prettyPrint) ? prettyPrint : true },
                { "quotaUser", quotaUser },
                { "userIp", userIp }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };
            _headers.Add("Authorization", string.Format("Bearer {0}", Configuration.OAuthAccessToken));

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Delete(_queryUrl, _headers, null);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

    }
} 