/*
 * GmailAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities; 
using GmailAPI.PCL.Http.Client;
using GmailAPI.PCL.Http.Response;
using GmailAPI.Tests.Helpers;
using NUnit.Framework;
using GmailAPI.PCL.Controllers;
using GmailAPI.PCL.Models;
using GmailAPI.PCL.Exceptions;

namespace GmailAPI.Tests
{
    [TestFixture]
    public class LabelsControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static LabelsController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Labels;
        }

        /// <summary>
        /// Lists all labels in the user's mailbox. 
        /// </summary>
        [Test]
        public async Task TestList1() 
        {
            // Parameters for the API call
            string userId = "me";
            string alt = "json";
            string fields = null;
            string key = null;
            string oauthToken = null;
            bool? prettyPrint = true;
            string quotaUser = null;
            string userIp = null;

            // Perform API call
            ListLabelsResponse result = null;

            try
            {
                result = await controller.ListAsync(userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.IsTrue(TestHelper.IsJsonObjectProperSubsetOf(
                    "{  \"labels\": [    {      \"labelListVisibility\": \"labelHide\",      \"messageListVisibility\": \"hide\",      \"type\": \"system\"    }  ]}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody), 
                    false, true, false),
                    "Response body should have matching keys");
        }

        /// <summary>
        /// Creates a new label. 
        /// </summary>
        [Test]
        public async Task TestCreate1() 
        {
            // Parameters for the API call
            Label body = APIHelper.JsonDeserialize<Label>("{  \"labelListVisibility\": \"labelHide\",  \"messageListVisibility\": \"hide\",  \"type\": \"system\"}");
            string userId = "me";
            string alt = "json";
            string fields = null;
            string key = null;
            string oauthToken = null;
            bool? prettyPrint = true;
            string quotaUser = null;
            string userIp = null;

            // Perform API call
            Label result = null;

            try
            {
                result = await controller.CreateAsync(body, userId, alt, fields, key, oauthToken, prettyPrint, quotaUser, userIp);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", null);

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.IsTrue(TestHelper.IsJsonObjectProperSubsetOf(
                    "{  \"labelListVisibility\": \"labelHide\",  \"messageListVisibility\": \"hide\",  \"type\": \"system\"}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody), 
                    false, true, false),
                    "Response body should have matching keys");
        }

    }
}