/*
 * GmailAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities;

namespace GmailAPI.PCL.Models
{
    public class History : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string id;
        private List<HistoryLabelAdded> labelsAdded;
        private List<HistoryLabelRemoved> labelsRemoved;
        private List<Message> messages;
        private List<HistoryMessageAdded> messagesAdded;
        private List<HistoryMessageDeleted> messagesDeleted;

        /// <summary>
        /// The mailbox sequence ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Labels added to messages in this history record.
        /// </summary>
        [JsonProperty("labelsAdded")]
        public List<HistoryLabelAdded> LabelsAdded 
        { 
            get 
            {
                return this.labelsAdded; 
            } 
            set 
            {
                this.labelsAdded = value;
                onPropertyChanged("LabelsAdded");
            }
        }

        /// <summary>
        /// Labels removed from messages in this history record.
        /// </summary>
        [JsonProperty("labelsRemoved")]
        public List<HistoryLabelRemoved> LabelsRemoved 
        { 
            get 
            {
                return this.labelsRemoved; 
            } 
            set 
            {
                this.labelsRemoved = value;
                onPropertyChanged("LabelsRemoved");
            }
        }

        /// <summary>
        /// List of messages changed in this history record. The fields for specific change types, such as messagesAdded may duplicate messages in this field. We recommend using the specific change-type fields instead of this.
        /// </summary>
        [JsonProperty("messages")]
        public List<Message> Messages 
        { 
            get 
            {
                return this.messages; 
            } 
            set 
            {
                this.messages = value;
                onPropertyChanged("Messages");
            }
        }

        /// <summary>
        /// Messages added to the mailbox in this history record.
        /// </summary>
        [JsonProperty("messagesAdded")]
        public List<HistoryMessageAdded> MessagesAdded 
        { 
            get 
            {
                return this.messagesAdded; 
            } 
            set 
            {
                this.messagesAdded = value;
                onPropertyChanged("MessagesAdded");
            }
        }

        /// <summary>
        /// Messages deleted (not Trashed) from the mailbox in this history record.
        /// </summary>
        [JsonProperty("messagesDeleted")]
        public List<HistoryMessageDeleted> MessagesDeleted 
        { 
            get 
            {
                return this.messagesDeleted; 
            } 
            set 
            {
                this.messagesDeleted = value;
                onPropertyChanged("MessagesDeleted");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 