/*
 * GmailAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities;

namespace GmailAPI.PCL.Models
{
    public class HistoryLabelAdded : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private List<string> labelIds;
        private Message message;

        /// <summary>
        /// Label IDs added to the message.
        /// </summary>
        [JsonProperty("labelIds")]
        public List<string> LabelIds 
        { 
            get 
            {
                return this.labelIds; 
            } 
            set 
            {
                this.labelIds = value;
                onPropertyChanged("LabelIds");
            }
        }

        /// <summary>
        /// An email message.
        /// </summary>
        [JsonProperty("message")]
        public Message Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 