/*
 * GmailAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities;

namespace GmailAPI.PCL.Models
{
    public class ListHistoryResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private List<History> history;
        private string historyId;
        private string nextPageToken;

        /// <summary>
        /// List of history records. Any messages contained in the response will typically only have id and threadId fields populated.
        /// </summary>
        [JsonProperty("history")]
        public List<History> History 
        { 
            get 
            {
                return this.history; 
            } 
            set 
            {
                this.history = value;
                onPropertyChanged("History");
            }
        }

        /// <summary>
        /// The ID of the mailbox's current history record.
        /// </summary>
        [JsonProperty("historyId")]
        public string HistoryId 
        { 
            get 
            {
                return this.historyId; 
            } 
            set 
            {
                this.historyId = value;
                onPropertyChanged("HistoryId");
            }
        }

        /// <summary>
        /// Page token to retrieve the next page of results in the list.
        /// </summary>
        [JsonProperty("nextPageToken")]
        public string NextPageToken 
        { 
            get 
            {
                return this.nextPageToken; 
            } 
            set 
            {
                this.nextPageToken = value;
                onPropertyChanged("NextPageToken");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 