/*
 * GmailAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities;

namespace GmailAPI.PCL.Models
{
    public class ModifyMessageRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private List<string> addLabelIds;
        private List<string> removeLabelIds;

        /// <summary>
        /// A list of IDs of labels to add to this message.
        /// </summary>
        [JsonProperty("addLabelIds")]
        public List<string> AddLabelIds 
        { 
            get 
            {
                return this.addLabelIds; 
            } 
            set 
            {
                this.addLabelIds = value;
                onPropertyChanged("AddLabelIds");
            }
        }

        /// <summary>
        /// A list IDs of labels to remove from this message.
        /// </summary>
        [JsonProperty("removeLabelIds")]
        public List<string> RemoveLabelIds 
        { 
            get 
            {
                return this.removeLabelIds; 
            } 
            set 
            {
                this.removeLabelIds = value;
                onPropertyChanged("RemoveLabelIds");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 