/*
 * GmailAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities;

namespace GmailAPI.PCL.Models
{
    public class Profile : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string emailAddress;
        private string historyId;
        private double? messagesTotal;
        private double? threadsTotal;

        /// <summary>
        /// The user's email address.
        /// </summary>
        [JsonProperty("emailAddress")]
        public string EmailAddress 
        { 
            get 
            {
                return this.emailAddress; 
            } 
            set 
            {
                this.emailAddress = value;
                onPropertyChanged("EmailAddress");
            }
        }

        /// <summary>
        /// The ID of the mailbox's current history record.
        /// </summary>
        [JsonProperty("historyId")]
        public string HistoryId 
        { 
            get 
            {
                return this.historyId; 
            } 
            set 
            {
                this.historyId = value;
                onPropertyChanged("HistoryId");
            }
        }

        /// <summary>
        /// The total number of messages in the mailbox.
        /// </summary>
        [JsonProperty("messagesTotal")]
        public double? MessagesTotal 
        { 
            get 
            {
                return this.messagesTotal; 
            } 
            set 
            {
                this.messagesTotal = value;
                onPropertyChanged("MessagesTotal");
            }
        }

        /// <summary>
        /// The total number of threads in the mailbox.
        /// </summary>
        [JsonProperty("threadsTotal")]
        public double? ThreadsTotal 
        { 
            get 
            {
                return this.threadsTotal; 
            } 
            set 
            {
                this.threadsTotal = value;
                onPropertyChanged("ThreadsTotal");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 