/*
 * GmailAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/27/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GmailAPI.PCL;
using GmailAPI.PCL.Utilities;

namespace GmailAPI.PCL.Models
{
    public class Thread : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string historyId;
        private string id;
        private List<Message> messages;
        private string snippet;

        /// <summary>
        /// The ID of the last history record that modified this thread.
        /// </summary>
        [JsonProperty("historyId")]
        public string HistoryId 
        { 
            get 
            {
                return this.historyId; 
            } 
            set 
            {
                this.historyId = value;
                onPropertyChanged("HistoryId");
            }
        }

        /// <summary>
        /// The unique ID of the thread.
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The list of messages in the thread.
        /// </summary>
        [JsonProperty("messages")]
        public List<Message> Messages 
        { 
            get 
            {
                return this.messages; 
            } 
            set 
            {
                this.messages = value;
                onPropertyChanged("Messages");
            }
        }

        /// <summary>
        /// A short part of the message text.
        /// </summary>
        [JsonProperty("snippet")]
        public string Snippet 
        { 
            get 
            {
                return this.snippet; 
            } 
            set 
            {
                this.snippet = value;
                onPropertyChanged("Snippet");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 